package com.model;

// Generated 25 févr. 2014 18:04:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table( name = "admin"
        , schema = "public" )
public class Admin implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int               idAdmin;
    private String            motPasse;
    private String            login;

    public Admin() {
    }

    public Admin( int idAdmin ) {
        this.idAdmin = idAdmin;
    }

    public Admin( int idAdmin, String motPasse, String login ) {
        this.idAdmin = idAdmin;
        this.motPasse = motPasse;
        this.login = login;
    }

    @Id
    @Column( name = "id_admin", unique = true, nullable = false )
    public int getIdAdmin() {
        return this.idAdmin;
    }

    public void setIdAdmin( int idAdmin ) {
        this.idAdmin = idAdmin;
    }

    @Column( name = "mot_passe" )
    public String getMotPasse() {
        return this.motPasse;
    }

    public void setMotPasse( String motPasse ) {
        this.motPasse = motPasse;
    }

    @Column( name = "login" )
    public String getLogin() {
        return this.login;
    }

    public void setLogin( String login ) {
        this.login = login;
    }

}
