package com.model;

// Generated 25 févr. 2014 18:04:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Filtre generated by hbm2java
 */
@Entity
@Table( name = "filtre"
        , schema = "public" )
public class Filtre implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int               idFiltre;
    private Utilisateur       utilisateur;
    private String            typeAnnonce;
    private String            typeBien;
    private Boolean           etatFiltre;
    private Integer           surface;
    private Integer           prix;

    public Filtre() {
    }

    public Filtre( int idFiltre, Utilisateur utilisateur ) {
        this.idFiltre = idFiltre;
        this.utilisateur = utilisateur;
    }

    public Filtre( int idFiltre, Utilisateur utilisateur, String typeAnnonce, String typeBien, Boolean etatFiltre,
            Integer surface, Integer prix ) {
        this.idFiltre = idFiltre;
        this.utilisateur = utilisateur;
        this.typeAnnonce = typeAnnonce;
        this.typeBien = typeBien;
        this.etatFiltre = etatFiltre;
        this.surface = surface;
        this.prix = prix;
    }

    @Id
    @Column( name = "id_filtre", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdFiltre() {
        return this.idFiltre;
    }

    public void setIdFiltre( int idFiltre ) {
        this.idFiltre = idFiltre;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_user", nullable = false )
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur( Utilisateur utilisateur ) {
        this.utilisateur = utilisateur;
    }

    @Column( name = "type_annonce" )
    public String getTypeAnnonce() {
        return this.typeAnnonce;
    }

    public void setTypeAnnonce( String typeAnnonce ) {
        this.typeAnnonce = typeAnnonce;
    }

    @Column( name = "type_bien" )
    public String getTypeBien() {
        return this.typeBien;
    }

    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }

    @Column( name = "etat_filtre" )
    public Boolean getEtatFiltre() {
        return this.etatFiltre;
    }

    public void setEtatFiltre( Boolean etatFiltre ) {
        this.etatFiltre = etatFiltre;
    }

    @Column( name = "surface" )
    public Integer getSurface() {
        return this.surface;
    }

    public void setSurface( Integer surface ) {
        this.surface = surface;
    }

    @Column( name = "prix" )
    public Integer getPrix() {
        return this.prix;
    }

    public void setPrix( Integer prix ) {
        this.prix = prix;
    }

}
