package com.model;

// Generated 25 févr. 2014 18:04:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table( name = "photo"
        , schema = "public" )
public class Photo implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int               idPhoto;
    private Annonce           annonce;
    private Long              photo;
    private byte[]            bytes;

    public Photo() {
    }

    public Photo( int idPhoto ) {
        this.idPhoto = idPhoto;
    }

    public Photo( int idPhoto, Annonce annonce, Long photo ) {
        this.idPhoto = idPhoto;
        this.annonce = annonce;
        this.photo = photo;
    }

    @Id
    @Column( name = "id_photo", unique = true, nullable = false )
    public int getIdPhoto() {
        return this.idPhoto;
    }

    public void setIdPhoto( int idPhoto ) {
        this.idPhoto = idPhoto;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_annonce" )
    public Annonce getAnnonce() {
        return this.annonce;
    }

    public void setAnnonce( Annonce annonce ) {
        this.annonce = annonce;
    }

    /*
     * @Column( name = "photo" ) public Long getPhoto() { return this.photo; }
     * 
     * public void setPhoto( Long photo ) { this.photo = photo; }
     */
    @Lob
    @Column( name = "photo" )
    public byte[] getBytes() {
        return bytes;
    }

    public void setBytes( byte[] bytes ) {
        this.bytes = bytes;
    }

}
