package com.model;

// Generated 25 févr. 2014 18:04:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table( name = "utilisateur"
        , schema = "public" )
public class Utilisateur implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int               idUser;
    private String            alias;
    private String            name;
    private String            prenom;
    private String            email;
    private Boolean           etat;
    private Set<Annonce>      annonces         = new HashSet<Annonce>( 0 );
    private Set<Filtre>       filtres          = new HashSet<Filtre>( 0 );

    public Utilisateur() {
    }

    public Utilisateur( int idUser ) {
        this.idUser = idUser;
    }

    public Utilisateur( int idUser, String alias, String name, String prenom, String email, Boolean etat,
            Set<Annonce> annonces, Set<Filtre> filtres ) {
        this.idUser = idUser;
        this.alias = alias;
        this.name = name;
        this.prenom = prenom;
        this.email = email;
        this.etat = etat;
        this.annonces = annonces;
        this.filtres = filtres;
    }

    @Id
    @Column( name = "id_user", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser( int idUser ) {
        this.idUser = idUser;
    }

    @Column( name = "alias" )
    public String getAlias() {
        return this.alias;
    }

    public void setAlias( String alias ) {
        this.alias = alias;
    }

    @Column( name = "name" )
    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    @Column( name = "prenom" )
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }

    @Column( name = "email" )
    public String getEmail() {
        return this.email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    @Column( name = "etat" )
    public Boolean getEtat() {
        return this.etat;
    }

    public void setEtat( Boolean etat ) {
        this.etat = etat;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Annonce> getAnnonces() {
        return this.annonces;
    }

    public void setAnnonces( Set<Annonce> annonces ) {
        this.annonces = annonces;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Filtre> getFiltres() {
        return this.filtres;
    }

    public void setFiltres( Set<Filtre> filtres ) {
        this.filtres = filtres;
    }

}
